= cmpitg's personal Emacs config
:Author: Nguyễn Hà Dương (cmpitg)
:Email: <cmpitg@gmail.com>
:toc: left
:toclevels: 4
:numbered:
:icons: font
:source-highlighter: pygments
:pygments-css: class
:imagesdirs: assets/images

// $ ulqui generate-html --from . --to docs

Let's start with a minimal standard config that

* has the package manager set up
* has necessary packages loaded
* has all convenient functions loaded
* has the environment set up

Since this configuration is written in literate programming style, there is
actually no need to modularize configuration into files.  Thus we have the one
and only +init.el+ file needed for Emacs to load.

== Customizable constants

* +*config-dir*+ is the directory where this set of configuration resides

.code::constants
[source,lisp,linenums]
----
(defvar *config-dir* (file-name-directory (or load-file-name
                                              (buffer-file-name))))

----

== Configuring package manager

.code::config-package-manager
[source,lisp,linenums]
----
;; include::package/add-repos

;; include::package/init

;; include::package/init-el-get

;; include::package/init-local

;; include::package/use-package
----

=== Adding useful repository

.code::package/add-repos
[source,lisp,linenums]
----
(require 'package)

(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/"))
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/"))

----

=== Initializing package manager

Initialize and fetch the list of available packages:

.code::package/init
[source,lisp,linenums]
----
(package-initialize)

;; Fetch the list of available packages
(when (not package-archive-contents)
  (package-refresh-contents))
----

Beside the default package manager, https://github.com/dimitri/el-get[el-get]
is comes in hand at times:

.code::package/init-el-get
[source,lisp,linenums]
----
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (cond
   ((fboundp 'el-get-self-update)
    (el-get-self-update))

   (t
    (url-retrieve
     "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
     (lambda (s)
       (goto-char (point-max))
       (eval-print-last-sexp))))))

;; el-get runs in sync mode
(el-get 'sync)

----

Besides packages managed by package manager, there are local packages that
need to be added to +load-path+ as well:

.code::package/init-local
[source,lisp,linenums]
----
(let ((local-package-dir (~get-config "local-packages/")))
  (dolist (package-dir (directory-files local-package-dir))
    (add-to-list 'load-path (~get-config local-package-dir package-dir))))

----

=== Load +use-package+

https://github.com/jwiegley/use-package[+use-package+] is an extremely
convenient and efficient way to load package.  It's a package itself, which
means we need to load it before everything else:

.code::package/use-package
[source,lisp,linenums]
----
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)

----


== Loading essential packages

First of all, local packages need to be taken care.  Packages that are not
available through package manager or their features are most appropriate at
some specific commit will be added as local packages.

.code::load-path-local-packages
[source,lisp,linenums]
----
;;
;; Add local packages to load-path
;;

(dolist (pkg (directory-files (~get-config "local-packages/")))
  (add-to-list 'load-path (~get-config "local-packages/" pkg)))

----


Essential packages are minimal necessary packages to make Emacs as useful as
possible.

.code::load-essential-packages
[source,lisp,linenums]
----
;;
;; Modern list processing library
;;

(use-package dash
  :ensure dash
  :config (dash-enable-font-lock))

;;
;; Hashtable
;;

(use-package ht
  :ensure ht)

;;
;; String processing
;;

(use-package s
  :ensure s)

;;
;; File/filesystem library
;;

(use-package f
  :ensure f)

;;
;; Smart completion framework
;;

(use-package helm-config
  :ensure helm
  :config (use-package helm))

;;
;; Various actions with 'thing' at current cursor
;;

(use-package thingatpt
  :ensure thingatpt)

;;
;; Multiple cursors
;;

(use-package multiple-cursors
  :ensure multiple-cursors)

;;
;; Expand region
;;

(use-package expand-region
  :ensure expand-region
  :commands er/expand-region)

;;
;; Live function signature at echo area
;;

(use-package eldoc
  :ensure eldoc)

;;
;; Better popup window management
;;

(use-package popwin
  :ensure popwin)

;;
;; Enhanced file management with Dired
;;

(use-package dired+
  :ensure dired+)

;;
;; Support for tar
;;

(use-package tar-mode
  :ensure tar-mode)

;;
;; Save and restore current editing point
;;

(use-package saveplace
  :ensure saveplace)

;;
;; Color theme
;;

(use-package color-theme
  :ensure color-theme)

;;
;; Smoother scrolling
;;

(use-package smooth-scrolling
  :ensure smooth-scrolling)

;;
;; Better ido
;;

(use-package flx-ido
  :ensure flx-ido)

;;
;; Jump between occurrences of a symbol
;;

(use-package smartscan
  :ensure smartscan)

;;
;; Better M-x
;;

(use-package smex
  :ensure smex)

;;
;; Find file with fuzzy matching
;;

(use-package fiplr
  :ensure fiplr)

;;
;; Editable Ack
;;

(use-package wgrep-ack
  :ensure wgrep-ack)

;;
;; Browsable kill ring
;;

(use-package browse-kill-ring
  :ensure browse-kill-ring)

;;
;; Simple tabbar
;;

(use-package tabbar-ruler
  :ensure tabbar-ruler)

;;
;; Async eval
;;

(el-get-install 'later-do)
(use-package later-do)

;;
;; Multiple scratch buffers
;;

(el-get-install 'multi-scratch)
(use-package multi-scratch)

;;
;; Manipulating Firefox/Thunderbird
;;

(el-get-install 'moz-repl)
(use-package moz)

;;
;; Display trailing whitespace
;;

(el-get-install 'whitespace)
(use-package whitespace
  :commands whitespace-mode)

;;
;; En/decoding JSON
;;

(el-get-install 'json-mode)
(use-package json-mode)

----



== Tweaking

.code::tweak
[source,lisp,linenums]
----
(defvar *electrify-return-match*
  "[\]\)]"
  ;; "[\]}\)\"]"
  "If this regexp matches the text after the cursor, do an
\"electric\" return.")
----


== Config helpers

.code::config-helpers
[source,lisp,linenums]
----
;; include::config-helpers/get-path
----


=== Getting path to a file/directory in the configuration directory

.code::config-helpers/get-path
[source,lisp,linenums]
----
(defun ~get-config (&rest paths)
  "Returns path to a config file or directory."
  (apply 'concat *config-dir* paths))

----

== Putting all together

Here is our +init.el+ after putting all things together:

.file::src/init.el
[source,lisp,linenums]
----
;; include::constants

;; include::config-helpers

;; include::config-package-manager

;; include::load-path-local-packages

;; include::load-essential-packages

;; include::tweak

;; (load "/m/src/emacs-cmpitg-rewrite/old/init-essential-packages.el")
----
