= cmpitg's personal Emacs config
:Author: Nguyễn Hà Dương (cmpitg)
:Email: <cmpitg@gmail.com>
:toc: left
:toclevels: 4
:numbered:
:icons: font
:source-highlighter: pygments
:pygments-css: class
:imagesdirs: assets/images

// $ ulqui generate-html --from . --to docs

Let's start with a minimal standard config that

* has the package manager set up
* has necessary packages loaded
* has all convenient functions loaded
* has the environment set up

Since this configuration is written in literate programming style, there is
actually no need to modularize configuration into files.  Thus we have the one
and only +init.el+ file needed for Emacs to load.

== Customizable constants

* +*config-dir*+ is the directory where this set of configuration resides

.code::constants
[source,lisp,linenums]
----
(defvar *config-dir* (file-name-directory (or load-file-name
                                              (buffer-file-name))))

----

== Configuring package manager

.code::config-package-manager
[source,lisp,linenums]
----
;; include::package/add-repos

;; include::package/init

;; include::package/init-el-get

;; include::package/init-local

;; include::package/use-package
----

=== Adding useful repository

.code::package/add-repos
[source,lisp,linenums]
----
(require 'package)

(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/"))
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/"))

----

=== Initializing package manager

Initialize and fetch the list of available packages:

.code::package/init
[source,lisp,linenums]
----
(package-initialize)

;; Fetch the list of available packages
(when (not package-archive-contents)
  (package-refresh-contents))
----

Beside the default package manager, https://github.com/dimitri/el-get[el-get]
is comes in hand at times:

.code::package/init-el-get
[source,lisp,linenums]
----
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (cond
   ((fboundp 'el-get-self-update)
    (el-get-self-update))

   (t
    (url-retrieve
     "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
     (lambda (s)
       (goto-char (point-max))
       (eval-print-last-sexp))))))

;; el-get runs in sync mode
(el-get 'sync)

----

Besides packages managed by package manager, there are local packages that
need to be added to +load-path+ as well:

.code::package/init-local
[source,lisp,linenums]
----
(let ((local-package-dir (~get-config "local-packages/")))
  (dolist (package-dir (directory-files local-package-dir))
    (add-to-list 'load-path (~get-config local-package-dir package-dir))))

----

=== Load +use-package+

https://github.com/jwiegley/use-package[+use-package+] is an extremely
convenient and efficient way to load package.  It's a package itself, which
means we need to load it before everything else:

.code::package/use-package
[source,lisp,linenums]
----
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)

----


== Loading essential packages

Essential packages are minimal necessary packages to make Emacs as useful as
possible.

.code::load-essential-packages
[source,lisp,linenums]
----
(defvar *essential-elpa-packages*
  '(dash                                ; "Modern" list processing
    ht                                  ; The missing hashtable library
    s                                   ; "Modern" string processing
    f                                   ; "Modern" file APIs
    cl                                  ; Common Lisp subset in Emacs Lisp
    cl-lib                              ; Common Lisp library
    helm                                ; Smart completion framework
    thingatpt                           ; Getting thing at current pointg
    multiple-cursors                    ; Sublime-like multiple cursors
    expand-region                       ; Expand selection based-on semantic
                                        ; units
    eldoc                               ; Echo area function signature
    popwin                              ; Better popwin window management,
                                        ; dispose with Esc or C-g
    dired+                              ; Enhanced Dired
    tar-mode                            ; Supports for tar
    saveplace                           ; Save and restore current editing
                                        ; point
    color-theme
    smooth-scrolling                    ; Smoother scrolling
    flx-ido                             ; Better ido
    smartscan                           ; Jump between occurrences of a symbol
    smex                                ; Better M-x
    fiplr                               ; Find file with fuzzy matching
    wgrep-ack                           ; Edittable Ack
    browse-kill-ring                    ; Browsable kill ring
    tabbar-ruler                        ; Tabbar
    )
  "Essential ELPA packages that are vital to this config.")

(defvar *essential-el-get-packages*
  '(later-do                            ; Async eval
    multi-scratch                       ; Multiple scratch buffers
    moz-repl                            ; MozRepl
    whitespace                          ; Display trailing whitespace
    json-mode                           ; For en/decoding JSON
    )
  "Essential packages that cannot be installed with ELPA but
  el-get.")

(dolist (pkg *essential-elpa-packages*)
  (eval `(use-package ,pkg
           :ensure ,pkg)))

(dolist (pkg *essential-el-get-packages*)
  (el-get-install pkg)
  (eval `(use-package ,pkg)))

----

== Config helpers

.code::config-helpers
[source,lisp,linenums]
----
;; include::config-helpers/get-path
----


=== Getting path to a file/directory in the configuration directory

.code::config-helpers/get-path
[source,lisp,linenums]
----
(defun ~get-config (&rest paths)
  "Returns path to a config file or directory."
  (apply 'concat *config-dir* paths))

----

== Putting all together

Here is our +init.el+ after putting all things together:

.file::src/init.el
[source,lisp,linenums]
----
;; include::constants

;; include::config-helpers

;; include::config-package-manager

;; include::load-essential-packages
----
