= Rmacs - cmpitg's Emacs

This documentation is a work in progress.  At this point in time please consult the source code (in `src/`) directly for in-depth documentation.

Emacs is considered an editor framework, providing building blocks to build editor and much more.  This repo contains my personal Emacs configuration, which, though heavily customized, could potentially be adopted to different users.  The idea is to use Emacs Lisp to push Emacs to its limit, morphing it to different shapes depending on the use cases.  Currently I'm running Emacs as:

* Basic text editor (with `rmacs minimal`),
* Full-blown text editor with IDE-like features (with `rmacs edit`),
* Email browser (with `rmacs mail`),
* Note taker (with `rmacs notes`).

== Architecture

With the entrypoint being `rmacs` script, Rmacs could be run in different so-called *shapes*.  Each shape defines a use case for Rmacs to run:

* Running a shape is essentially loading Emacs with a configuration set.  By default each shape loads the `minimal` configuration, then continues with specific configuration corresponding to its use case.

* Each shape runs an https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html[Emacs server] behind the scene, denoted by a server `name` (which could be passed by specifying the `--name` command line argument) with the socket directory being `/tmp/emacs${UID}`.  Rmacs doesn't add any additional layer on top of the default IPC machanism provided by Emacs so `emacsclient` could be used to interact with the Emacs server.

The `minimal` configuration contains some deliberate UX design that all of other shapes follow.  It tries to stay lean in a practical manner.

== Requirements

* Emacs 26.1+
* Python 3+
* GNU Make 4.1+.  Supposedly any version of modern Make implementation could work.
* The `${HOME}/bin` directory exists, containing executables for the current user.

== Installation

* Installing dependencies:
+
[source,sh]
----
make install-deps
----

* Installing Rmacs by symlinking the executable to `${HOME}/bin`:
+
[source,sh]
----
make install-bin
----

== Running

For full documentation, run `rmacs --help`.

=== Emacs as a basic text editor

[source,sh]
----
rmacs minimal <path>
----

=== Emacs as text editor

[source,sh]
----
rmacs edit <path>
----

=== Emacs as mail browser (with https://www.djcbsoftware.nl/code/mu/mu4e.html[mu4e])

[source,sh]
----
rmacs mail
----

=== Emacs as note taker

[source,sh]
----
rmacs notes
----

=== Communicating with a running Rmacs server

[source,sh]
----
rmacs --name <server-name> eval <expression>
----

== Selective workflows with `rmacs edit`

=== Python development

==== Project setup

Do this once for each new project:

* Open a file in the project
* `M-x pyvenv-workon` and choose the appropriate environment
* `M-x elpy-config` and install necessary dependencies

==== Working on an available project

* `M-x pyvenv-workon`
* Have fun
