= cmpitg's Emacs config

This documentation is out-dated.

TODO: Create a Make rule to generate the default configuration

[source,emacs-lisp]
----
(setq user-full-name "Ha-Duong Nguyen"
      user-mail-address "cmpitg@gmail.com"
      *toolbox-path* "/m/toolbox/Toolbox.adoc"
      *saved-macro-path* ""
      *scratch-dir* "/m/scratch/"
      *sbcl-bin-path* ""
      *quicklisp-path* (expand-file-name "~/quicklisp/")
      *notes-path* ""
      *conda-home-path* "/m/opt/miniconda3")
----

== Requirements

* Emacs 26.1+
* Python 3+
* GNU Make 4.1+.  Supposedly any version of modern Make implementation could work but I haven't yet tested.
* The `${HOME}/bin` directory exists, containing executables for the current user.

== Installation

* Installing dependencies:
+
[source,sh]
----
make install-deps
----

* Installing Rmacs by symlinking the executable to `${HOME}/bin`:
+
[source,sh]
----
make install-bin
----

== How to run

* Environment variables:
** `EMACS_PORT`
** `EMACS_FORCE_TOGGLE_DEBUG_ON_ERROR`
** `EMACS_NO_EXPERIMENTAL`
** `EMACS_ENABLED_MAIL`
** `EMACS_ENABLED_NOTES`

* High-level entry point: `rmacs`

* Low-level entry point: `emacs-cmpitg`

=== Emacs as text editor

[source,sh]
----
rmacs edit <path>
----

=== Emacs as mail browser (mu4e)

[source,sh]
----
rmacs mail
----

=== Emacs as note taker

[source,sh]
----
rmacs notes
----

== Python development workflow

=== Project setup

Do this once for each new project:

* Open a file in the project
* `M-x pyvenv-workon` and choose the appropriate virtual env
* `M-x elpy-config` and install necessary dependencies

=== Working on an available project

* `M-x pyvenv-workon`
* Have fun
