= Yet another Emacs configuration

== Guiding Principles

* Don't make me think!
** That it doesn't matter if a series of editing commands is long, as long as
   the mental load is kept minimal, the config delivers its goal.
*** E.g. If sometimes reaching for the mouse imposes physical movement but
    less mental load, enabling actions with the mouse is better than forcing
    users to stay on the keyboard.
*** E.g. Contrary to a popular belief, jumping to a line based on relative
    number (e.g. jump 9 lines forward) might lead to fewer editing commands
    but heavier mental load, i.e. counting/or reading a the (relative) line
    number, then type it might be more mentally taxing than just throwing and
    clicking the mouse on the desire place.
** There is no one true way to edit, e.g. selecting text might be done by
   holding the `Shift` key, or using the mouse, or using a visual/selection
   mode in a modal editing extension, etc.  Which way is most optimal depends
   on the mental of the current workflow.

* Integrating (not integrated) Development Environment:
** That Emacs should not try to reinvent the wheel.  Unless there is a
   significant increase in cost, i.e. maintenance effort, mental load, instead
   of reimplementing things in Emacs, try to interact with external tooling as
   much as possible.
*** E.g. The Helix text editor implements interesting and efficient ways of
    editing text, e.g. select-then-act modal.  If that is to be desired, one
    could quickly invoke Helix in an Emacs session.  It is not necessary to
    reimplement Helix features in Emacs.
*** E.g. Running terminal emulator in Emacs is requires understanding of how
    and when keybindings are forwarded to the terminal.  This might
    unnecessarily complex the workflow, which, in turn, increases the mental
    load.  It might be better to quickly summon and dismiss an external
    terminal emulator to do the job.
*** E.g. Lots of text processing tools are well-designed and well-tested.
    These include not only the traditional Sed, Awk, `wc`, `sort`, etc. but
    also https://jqlang.org/[Jq], https://github.com/mikefarah/yq[Yq],
    https://github.com/TomWright/dasel[Dasel], ... and the likes.  Invoking
    them in an editing session, e.g. by input-/output-piping, might be more
    useful than reimplementing parts of their functionality in Emacs Lisp.

== Useful Helpers

* To execute an external commands:
** Open a terminal emulation at the current working director: `~open-term-emu`
** Edit current file with the Helix text editor at the current point: ``
