= cmpitg's Emacs config

* Emacs server with https://github.com/cmpitg/emnode[Emnode] -- better
  interaction: cleaner, wider tools, ...

* By default:

** The
   https://www.gnu.org/software/emacs/manual/html_node/elisp/Error-Debugging.html[`toggle-debug-on-error`]
   option is disabled.  To turn it on, set the environment variable
   `EMACS_FORCE_TOGGLE_DEBUG_ON_ERROR` to `1`,
   e.g. `EMACS_FORCE_TOGGLE_DEBUG_ON_ERROR=1 emacs-cmpitg`.

** Emacs is loaded with my own experimental configuration
   link:src/experimental.el[`experimental.el`].  To disable this feature, set
   the environment variable `EMACS_NO_EXPERIMENTAL` to `1`,
   e.g. `EMACS_NO_EXPERIMENTAL=1 emacs-cmpitg`.

** If there is `.emacs-machine-specific.el` file in your home directory or
   `machine-specific.el` in the `src/` directory of this repo, they will be
   loaded.  Those files are meant to store machine-specific configuration.

== Python development workflow

=== Project setup

Do this once for each new project:

* Open a file in the project
* `M-x pyvenv-workon` and choose the appropriate virtual env
* `M-x elpy-config` and install necessary dependencies

=== Working on an available project

* `M-x pyvenv-workon`

* Have fun
