;;; acme-light-theme.el --- A color theme

;; Copyright (C) 2011 Cédric Mauclair

;; Adapted from naquadah-theme.el from Julien Danjou

;; Authors: Cédric Mauclair <cedric.mauclair@gmail.com>

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Code:

;; (deftheme acme-light
;;   "Acme light theme.")

(defun color-theme-acme-light ()
  (interactive)
  (deftheme acme-light
    "Acme light theme.")
  (let ((light-blue "#72A0CF")
        (pale-yellow "#D4F77F")
        (violet "#C66CD0")
        (green "#89E234")
        (blue "#374EAB")
        (yellow "#FCCD3A")
        (pink "#DE336D")
        (red "#8A0B0B")
        (violet-blue "#5337AD")
        (orange "#FFA500")
        (tomato "#FC683A")
        (background "#EEEEDD")
        (foreground "#262626")
        (shadow "#888a85"))
    (custom-theme-set-faces
     'acme-light
     `(default ((((min-colors 4096)) (:background ,background :foreground ,foreground))))
     '(bold ((t (:weight bold))))
     '(bold-italic ((t (:slant italic :weight bold))))
     '(border  ((t nil)))
     `(button  ((t (:foreground ,light-blue))))
     '(comint-highlight-input ((t (:italic t :bold t))))
     `(comint-highlight-prompt ((t (:foreground ,green))))
     '(completions-first-difference ((t (:inherit bold :background "red4" :foreground "yellow"))))
     '(cursor  ((t (:background "#55A096" :foreground "white"))))
     '(custom-button ((t (:background "light grey" :foreground "gray20" :box (:line-width 1 :color "dim gray")))))
     '(custom-button-mouse ((t (:background "dim gray" :foreground "white" :box (:line-width 1 :color "dim gray")))))
     '(custom-button-pressed ((t (:inherit custom-button :foreground "white"))))
     '(custom-button-pressed-unraised ((t (:foreground "magenta4"))))
     '(custom-button-unraised ((t (:inherit underline))))
     '(custom-comment ((t (:background "gray85"))))
     '(custom-comment-tag ((t (:foreground "blue4"))))
     '(custom-documentation ((t (:inherit default))))
     '(custom-face-tag ((t (:inherit custom-variable-tag))))
     '(custom-group-tag ((t (:inherit bold :foreground "dark red"))))
     '(custom-link ((t (:inherit link))))
     '(custom-state ((t (:foreground "sea green"))))
     '(custom-variable-button ((t (:underline t :weight bold))))
     '(custom-variable-tag ((t (:inherit bold :foreground "DodgerBlue3"))))
     '(custom-visibility ((t (:inherit link))))
     '(dired-directory ((t (:inherit font-lock-function-name-face))))
     `(diff-added ((t (:foreground ,green))))
     `(diff-changed ((t (:foreground ,orange))))
     `(diff-removed ((t (:foreground ,red))))
     '(diff-hunk-header ((t (:bold t))))
     `(diff-function ((t (:foreground ,orange))))
     '(diff-header ((t (:background "grey10"))))
     '(diff-file-header ((t (:background nil :foreground "white"))))
     '(dired-flagged ((t (:inherit font-lock-warning-face))))
     '(dired-header ((t (:inherit bold))))
     '(dired-ignored ((t (:inherit shadow))))
     '(dired-mark ((t (:inherit font-lock-constant-face))))
     '(dired-marked ((t (:inherit font-lock-constant-face))))
     '(dired-perm-write ((t (:inherit font-lock-warning-face))))
     '(dired-symlink ((t (:inherit font-lock-keyword-face :slant italic))))
     '(dired-warning ((t (:inherit font-lock-warning-face))))
     '(escape-glyph ((t (:foreground "brown1"))))
     '(fixed-pitch ((t (:height 0.9))))
     '(font-latex-bold-face ((t (:inherit bold))))
     '(font-latex-doctex-documentation-face ((t (:background "#333"))))
     '(font-latex-doctex-preprocessor-face ((t (:inherit (font-latex-doctex-documentation-face font-lock-preprocessor-face)))))
     '(font-latex-italic-face ((t (:inherit italic))))
     '(font-latex-math-face ((t (:inherit italic :foreground "green4"))))
     '(font-latex-sectioning-5-face ((t (:inherit (bold font-lock-type-face variable-pitch)))))
     '(font-latex-slide-title-face ((t (:inherit font-latex-sectioning-2-face))))
     '(font-latex-string-face ((t (:inherit font-lock-string-face))))
     '(font-latex-verbatim-face ((t (:inherit fixed-pitch))))
     '(font-latex-warning-face ((t (:inherit font-lock-warning-face))))
     '(font-lock-builtin-face ((t (:foreground "8B008B"))))
     '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
     '(font-lock-comment-face ((t (:foreground "gray60"))))
     '(font-lock-constant-face ((t (:foreground "#B452CD"))))
     '(font-lock-doc-face ((t (:inherit italic :foreground "VioletRed4"))))
     '(font-lock-function-name-face ((t (:foreground "#00688B"))))
     '(font-lock-keyword-face ((t (:foreground "purple"))))
     '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face bold)))))
     '(font-lock-regexp-grouping-backslash ((t (:inherit bold :underline "red2"))))
     '(font-lock-regexp-grouping-construct ((t (:inherit font-lock-regexp-grouping-backslash))))
     '(font-lock-string-face ((t (:inherit italic :foreground "#CD5555"))))
     '(font-lock-type-face ((t (:foreground "green4"))))
     '(font-lock-variable-name-face ((t (:foreground "#00688B"))))
     '(font-lock-warning-face ((t (:inherit bold :foreground "red4"))))
     '(fringe ((t (:background "gray75"))))
     '(git-commit-summary-face ((t (:bold t))))
     `(git-commit-branch-face ((t (:foreground ,orange :bold t))))
     '(git-commit-nonempty-second-line-face ((t (:foreground "red"))))
     '(git-commit-comment-face ((t (:inherit font-lock-comment-face))))
     '(git-commit-known-pseudo-header-face ((t (:inherit gnus-header-name-face))))
     '(git-commit-pseudo-header-face ((t (:inherit gnus-header-content))))
     '(header-line ((t (:inherit (mode-line bold)))))
     '(highlight ((t (:background "DarkSeaGreen2"))))
     '(highlight-current-line-face ((t (:inverse-video t))))
     '(hl-line ((t (:background "#191919"))))
     '(ibuffer-header-face ((t (:inherit (font-lock-type-face bold)))))
     '(isearch ((t (:inherit bold :background "DeepSkyBlue4" :foreground "LightSkyBlue1"))))
     '(italic  ((t (:slant italic))))
     '(lazy-highlight ((t (:background "Pale Turquoise"))))
     '(link ((t (:background "ivory2" :foreground "DodgerBlue3" :box (:line-width 1 :color "DodgerBlue3") :underline nil))))
     '(link-visited ((t (:inherit link :foreground "magenta4" :box (:line-width 1 :color "magenta4")))))
     '(match ((t (:background "yellow2"))))
     '(menu ((t nil)))
     '(minibuffer-prompt ((t (:inherit bold :foreground "SteelBlue4"))))
     '(mode-line ((t (:background "gray70" :foreground "gray20"  :inverse-video nil :box (:line-width -1 :color "gray45")))))
     '(mode-line-buffer-id ((t (:bold t))))
     '(mode-line-emphasis ((t (:inherit bold))))
     '(mode-line-highlight ((t (:inverse-video t))))
     '(mode-line-inactive ((t (:inherit mode-line :background "gray40" :foreground "gray80" :box (:line-width -1 :color "gray50")))))
     '(mode-line-buffer-id ((t (:bold t))))
     '(mouse ((t nil)))
     '(mumamo-background-chunk-major ((t (:background "gray70"))))
     '(mumamo-background-chunk-submode1 ((t (:background "gray70"))))
     '(mumamo-background-chunk-submode2 ((t (:background "gray70"))))
     '(mumamo-background-chunk-submode3 ((t (:background "gray70"))))
     '(mumamo-background-chunk-submode4 ((t (:background "gray70"))))
     '(nobreak-space ((t (:inherit escape-glyph :underline t))))
     '(org-hide ((t (:foreground "#252a2b"))))
     '(org-level-1 ((t (:bold t :foreground "#4788cc" :height 1.2))))
     '(org-level-2 ((t (:bold t :foreground "#6ac214" :height 1.1))))
     '(org-level-3 ((t (:bold t :foreground "#edd400" :height 1.0))))
     '(org-level-4 ((t (:bold t :foreground "tomato" :height 1.0))))
     '(org-footnote  ((t (:underline t :foreground "magenta3"))))
     '(org-link ((t (:foreground "SkyBlue2"))))
     '(org-special-keyword ((t (:foreground "brown1"))))
     '(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
     '(org-block ((t (:foreground "#bbbbbc"))))
     '(org-quote ((t (:inherit org-block :slant italic))))
     '(org-verse ((t (:inherit org-block :slant italic))))
     '(org-todo ((t (:bold t :foreground "#ff2020"))))
     '(org-done ((t (:bold t :foreground "forest green"))))
     '(org-mode-line-clock ((t (:foreground "#cc77ff" :background nil))))
     '(org-date ((t (:underline nil :foreground "#edd466" :background nil))))
     '(org-agenda-date ((t (:underline nil :foreground "SkyBlue2" :height 1.2))))
     '(org-agenda-date-today ((t (:inherit org-agenda-date :foreground "#edd466" :weight bold))))
     '(org-agenda-date-telecommuting ((t (:inherit org-agenda-date :foreground "#ffbb22" :weight bold))))
     '(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "brown3" :weight bold))))
     '(paren-face-match ((t (:inherit show-paren-match))))
     '(paren-face-mismatch ((t (:inherit show-paren-mismatch))))
     '(paren-face-no-match ((t (:inherit completions-first-difference))))
     '(proced-mark ((t (:inherit dired-mark))))
     '(proced-marked ((t (:inherit dired-marked))))
     '(proced-sort-header ((t (:inherit dired-header))))
     '(region ((t (:background "LightGoldenRod2"))))
     '(scroll-bar ((t nil)))
     '(secondary-selection ((t (:inherit region :inverse-video t))))
     `(shadow ((t (:foreground ,shadow))))
     '(show-paren-match ((t (:background "LightBlue4" :foreground "gray5"))))
     '(show-paren-mismatch ((t (:background "pink" :foreground "PaleVioletRed4"))))
     '(tool-bar ((t nil)))
     '(tooltip ((t (:inherit variable-pitch :background "light yellow" :foreground "black"))))
     '(trailing-whitespace ((t (:background "red1"))))
     '(underline ((t (:underline t))))
     '(variable-pitch ((t (:family "Sans Serif"))))
     '(vertical-border ((t (:foreground "black"))))
     '(widget-field ((t (:inherit italic :background "yellow3" :foreground "black"))))
     '(widget-single-line-field ((t (:inherit widget-field)))))))

(provide 'color-theme-acme-light)

;;; color-theme-acme-light.el ends here
